version: '3.3'
services:
  sharegpt:
    build: .
    restart: always
    environment:
      TWITTER_CLIENT_ID:
      TWITTER_CLIENT_SECRET:
      TWITTER_AUTH_TOKEN:
      NEXTAUTH_URL:
      NEXTAUTH_SECRET:
      DATABASE_URL: mysql://user:password@db:3306/db
      UPSTASH_REDIS_REST_TOKEN:
      UPSTASH_REDIS_REST_URL:
    ports:
      - '3000:3000'
    expose:
      - '3000'

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: